"""Builds game.bundle.js: a classic (non-module) script that works from file://.
Contains Three.js r159 (MIT, vendor/three-0.159.0.min.js), game.css, and the textures as data URIs.
Run after editing game.js or game.css:  python3 build_bundle.py
"""
import base64, json, os, re
D = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(D, 'game.js')).read()
three = open(os.path.join(D, 'vendor', 'three-0.159.0.min.js')).read()
three = re.sub(r"^console\.warn\([^\n]*?\),", "void 0,", three, count=1)  # drop the r150 deprecation warning
css = open(os.path.join(D, 'game.css')).read()
embed = {}
for n in ['floor-maple.jpg', 'backdrop-fb.jpg', 'backdrop-vc.jpg']:
    p = os.path.join(D, 'assets', n)
    if os.path.exists(p):
        embed[n] = 'data:image/jpeg;base64,' + base64.b64encode(open(p, 'rb').read()).decode()
rep = [
    (re.compile(r"^import \* as THREE from [^\n]+\n", re.M), ''),
    (re.compile(r"^const BASE = new URL\('\.', import\.meta\.url\)\.href;", re.M),
     "const BASE = (function () { try { var s = document.currentScript && document.currentScript.src; if (s) return new URL('.', s).href; } catch (e) {} return 'game/'; })();"),
    (re.compile(r"^const EMBED = \{\};", re.M), 'const EMBED = ' + json.dumps(embed) + ';'),
    (re.compile(r"^const EMBED_CSS = null;", re.M), 'const EMBED_CSS = ' + json.dumps(css) + ';'),
    (re.compile(r"^export default API;\s*$", re.M), ''),
]
for rx, b in rep:
    src, n = rx.subn(lambda m: b, src)
    assert n == 1, rx.pattern
assert 'import.meta' not in src and not re.search(r'^\s*(import|export)\s', src, re.M)
out = ("/* FINAL BOSS Boss Rush, classic build (works from file://). Generated by build_bundle.py from game.js. "
       "Includes Three.js r159, MIT License, Copyright 2010-2023 Three.js Authors. */\n"
       + "var __fbgPrevTHREE = window.THREE, __fbgPrevTag = window.__THREE__; try { delete window.__THREE__; } catch (e) { window.__THREE__ = undefined; }\n"
       + three + "\n;(function () {\n'use strict';\nvar THREE = window.THREE;\n"
       + "/* keep the page's own global THREE (for example r128) untouched */ if (__fbgPrevTHREE) window.THREE = __fbgPrevTHREE; if (__fbgPrevTag) window.__THREE__ = __fbgPrevTag;\n"
       + src + "\n})();\n")
open(os.path.join(D, 'game.bundle.js'), 'w').write(out)
print('game.bundle.js', round(len(out) / 1024), 'KB; embedded:', list(embed))
